<theme extends="frostillic.us" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="platform:/plugin/com.ibm.designer.domino.stylekits/schema/stylekit.xsd" >
	<resources>
		<bundle var="config" src="development.properties" target="xsp"/>
	</resources>
	
	<control>
		<name>ViewRoot</name>
		<property mode="concat">
			<name>pageTitle</name>
			<value>:: Development</value>
		</property>
	</control>
</theme>
