xsp.error.page.default=true
xsp.persistence.mode=file
xsp.library.depends=org.openntf.xsp.jakartaee.core,org.openntf.xsp.jakartaee.ui,org.openntf.xsp.microprofile
org.openntf.xsp.jakarta.rest.deferToFiles=true
org.openntf.xsp.jakarta.rest.path=/