require "ffi"

module Domino
	module API
		extend FFI::Library
		
		# some handy global constants
		NULLHANDLE = 0
		MAXUSERNAME = 256
		NAMES_LIST_AUTHENTICATED = 0x0001
		NAMES_LIST_PASSWORD_AUTHENTICATED = 0x0002
		NAMES_LIST_FULL_ADMIN_ACCESS = 0x0004
		ERR_MASK = 0x3fff
		
		# define the type names Domino uses for its API calls
		typedef :uint32, :DHANDLE
		typedef :uint32, :DWORD
		typedef :uint16, :WORD
		typedef :uint32, :HANDLE
		typedef :HANDLE, :WHANDLE
		typedef :WHANDLE, :HMODULE
		typedef :WORD, :STATUS
		typedef :HANDLE, :DBHANDLE
		typedef :DWORD, :NOTEID
		typedef :WORD, :HCOLLECTION
		typedef :uint16, :USHORT
		typedef :uint8, :BYTE
		typedef :uint32, :BOOL
		typedef :uint64, :DBID
		typedef :DHANDLE, :NOTEHANDLE
		typedef :uint64, :TIMEDATE_S	# for use in structures that don't care about the TIMEDATE value (like UNIVERSALNOTEID)
		typedef :WORD, :BLOCK
		typedef :double, :NUMBER
		typedef :DWORD, :HMIMEDIRECTORY
		typedef :pointer, :PMIMEENTITY
		typedef :int, :MIMESYMBOL
		typedef :pointer, :CCHANDLE
		typedef :pointer, :HCOMPUTE
		typedef :HANDLE, :FORMULAHANDLE
		typedef :DWORD, :MEMHANDLE
		typedef :MEMHANDLE, :HTMLHANDLE
		typedef :MEMHANDLE, :DXLEXPORTHANDLE
		typedef :double, :NUMBER
		
		MAXPATH = 256
    
		MAXTUMBLERLEVELS = 32
		MAXTUMBLERLEVELS_V2 = 8
		PERCENTILE_COUNT = 11
		
		# view open flags
		OPEN_REBUILD_INDEX = 0x0001
		OPEN_NOUPDATE = 0x0002
		OPEN_DO_NOT_CREATE = 0x0004
		OPEN_SHARED_VIEW_NOTE = 0x0010
		OPEN_REOPEN_COLLECTION = 0x0020
		
		# view read masks
		READ_MASK_NOTEID = 			0x00000001
		READ_MASK_NOTEUNID = 			0x00000002
		READ_MASK_NOTECLASS = 			0x00000004
		READ_MASK_INDEXSIBLINGS = 		0x00000008
		READ_MASK_INDEXCHILDREN = 		0x00000010
		READ_MASK_INDEXDESCENDANTS =		0x00000020
		READ_MASK_INDEXANYUNREAD =		0x00000040
		READ_MASK_INDENTLEVELS =		0x00000080
		READ_MASK_SCORE	=			0x00000200
		READ_MASK_INDEXUNREAD =			0x00000400
		READ_MASK_COLLECTIONSTATS = 		0x00000100
		READ_MASK_INDEXPOSITION = 		0x00004000
		READ_MASK_SUMMARYVALUES = 		0x00002000
		READ_MASK_SUMMARY = 			0x00008000
		
		# view navigator options
		NAVIGATE_CURRENT = 0
		NAVIGATE_NEXT = 1
		NAVIGATE_PARENT = 3
		NAVIGATE_CHILD = 4
		NAVIGATE_FIRST_PEER = 7
		NAVIGATE_LAST_PEER = 8
		NAVIGATE_CURRENT_MAIN = 11
		NAVIGATE_ALL_DESCENDANTS = 17
		NAVIGATE_NEXT_HIT = 29
		NAVIGATE_CURRENT_HIT = 31
		NAVIGATE_MASK =			0x007F
		NAVIGATE_MINLEVEL =		0x0100
		NAVIGATE_MAXLEVEL = 	0x0200
		NAVIGATE_CONTINUE = 	0x8000
		
		# Collations
		COLLATION_SIGNATURE = 0x44
		COLLATE_TYPE_KEY = 0
		COLLATE_TYPE_NOTEID = 3
		COLLATE_TYPE_TUMBLER = 6
		COLLATE_TYPE_CATEGORY = 7
		
		# ID Tables (DocumentCollection)
		DB_GETIDTABLE_VALIDATE = 0x00000001
		
		# view signals
		SIGNAL_MORE_TO_DO = 0x0020
		
		# Full-text search stuff
		FT_SEARCH_SET_COLL = 0x00000001
		FT_SEARCH_RET_IDTABLE = 0x00000010
		FT_SEARCH_NUMDOCS_ONLY = 0x00000002
		FT_SEARCH_REFINE = 0x00000004
		FT_SEARCH_SCORES = 0x00000008
		FT_SEARCH_SORT_DATE = 0x00000020
		FT_SEARCH_SORT_ASCEND = 0x00000040
		FT_SEARCH_TOP_SCORES = 0x00000080
		FT_SEARCH_STEM_WORDS = 0x00000200
		FT_SEARCH_THESAURUS_WORDS = 0x00000400
		FT_SEARCH_FUZZY = 0x00004000
		FT_SEARCH_EXT_RET_URL = 0x00008000
		FT_SEARCH_SORT_DATE_CREATED = 0x00010000
		FT_SEARCH_EXT_DOMAIN = 0x00040000
		FT_SEARCH_EXT_FILESYSTEM = 0x00100000
		FT_SEARCH_EXT_DATABASE = 0x00200000
		
		# Index search
		FIND_PARTIAL = 0x0001
		FIND_CASE_INSENSITIVE = 0x0002
		FIND_RETURN_DWORD = 0x0004
		FIND_ACCENT_INSENSITIVE = 0x0008
		FIND_UPDATE_IF_NOT_FOUND = 0x0020
		FIND_LESS_THAN = 0x0040
		FIND_FIRST_EQUAL = 0x0000
		FIND_LAST_EQUAL = 0x0080
		FIND_GREATER_THAN = 0x00C0
		FIND_EQUAL = 0x0800
		FIND_COMPARE_MASK = 0x08C0
		FIND_RANGE_OVERLAP = 0x0100
		FIND_RETURN_ANY_NON_CATEGORY_MATCH = 0x0200
		
		# Documnt/note access
		OPEN_SUMMARY = 0x0001
		OPEN_NOVERIFYDEFAULT = 0x0002
		OPEN_EXPAND = 0x0004
		OPEN_NOOBJECTS = 0x0008
		OPEN_SHARE = 0x0020
		OPEN_CANONICAL = 0x0040
		OPEN_MARK_READ = 0x0100
		OPEN_ABSTRACT = 0x0200
		OPEN_RESPONSE_ID_TABLE = 0x1000
		OPEN_WITH_FOLDERS = 0x00020000
		OPEN_RAW_RFC822_TEXT = 0x01000000
		OPEN_RAW_MIME_PART = 0x02000000
		OPEN_RAW_MIME = 0x01000000 | 0x02000000
		
		# It appears that Ruby doesn't make handy class methods when it doesn't
		# follow proper constant syntax, so these constants get an "F" at the start
		F_NOTE_DB = 0
		F_NOTE_ID = 1
		F_NOTE_OID = 2
		F_NOTE_CLASS = 3
		F_NOTE_MODIFIED = 4
		F_NOTE_PRIVILEGES = 5
		F_NOTE_FLAGS = 7
		F_NOTE_ACCESSED = 8
		F_NOTE_PARENT_NOTEID = 10
		F_NOTE_RESPONSE_COUNT = 11
		F_NOTE_RESPONSES = 12
		F_NOTE_ADDED_TO_FILE = 13
		F_NOTE_OBJSTORE_DB = 14
		
		NOTE_CLASS_DOCUMENT = 0x0001
		NOTE_CLASS_DATA = NOTE_CLASS_DOCUMENT
		NOTE_CLASS_INFO = 0x0002
		NOTE_CLASS_FORM = 0x0004
		NOTE_CLASS_VIEW = 0x0008
		NOTE_CLASS_ICON = 0x0010
		NOTE_CLASS_DESIGN = 0x0020
		NOTE_CLASS_ACL = 0x0040
		NOTE_CLASS_HELP_INDEX = 0x0080
		NOTE_CLASS_HELP = 0x0100
		NOTE_CLASS_FILTER = 0x0200
		NOTE_CLASS_FIELD = 0x0400
		NOTE_CLASS_REPLFORMULA = 0x0800
		NOTE_CLASS_PRIVATE = 0x1000
		NOTE_CLASS_DEFAULT = 0x8000
		NOTE_CLASS_NOTIFYDELETION = NOTE_CLASS_DEFAULT
		NOTE_CLASS_ALL = 0x7fff
		NOTE_CLASS_ALLNODATA = 0x7ffe
		NOTE_CLASS_NONE = 0x000
		NOTE_CLASS_SINGLE_INSTANCE = NOTE_CLASS_DESIGN | NOTE_CLASS_ACL | NOTE_CLASS_INFO | NOTE_CLASS_ICON | NOTE_CLASS_HELP_INDEX
		
		NOTE_ID_SPECIAL = 0xFFFF0000
		NOTEID_CATEGORY = 0x80000000
		NOTEID_CATEGORY_TOTAL = 0xC0000000
		NOTEID_CATEGORY_INDENT = 0x3F000000
		NOTEID_CATEGORY_ID = 0x00FFFFFF
		
		NOTE_FLAG_READONLY = 0x0001
		NOTE_FLAG_ABSTRACTED = 0x0002
		NOTE_FLAG_INCREMENTAL = 0x0004
		NOTE_FLAG_LINKED = 0x0020
		NOTE_FLAG_INCREMENTAL_FULL = 0x0040
		NOTE_FLAG_CANONICAL = 0x4000
		
		# item types, along with the CLASS_xxx constants they're based on
		CLASS_ERROR = (1 << 8)
		CLASS_UNAVAILABLE = (2 << 8)
		CLASS_TEXT = (5 << 8)
		CLASS_NUMBER = (3 << 8)
		CLASS_TIME = (4 << 8)
		CLASS_FORMULA = (6 << 8)
		CLASS_USERID = (7 << 8)
		CLASS_NOCOMPUTE = (0 << 8)
		
		TYPE_ERROR = 0 + CLASS_ERROR
		TYPE_UNAVAILABLE = 0 + CLASS_UNAVAILABLE
		TYPE_TEXT = 0 + CLASS_TEXT
		TYPE_TEXT_LIST = 1 + CLASS_TEXT
		TYPE_NUMBER = 0 + CLASS_NUMBER
		TYPE_NUMBER_RANGE = 1 + CLASS_NUMBER
		TYPE_TIME = 0 + CLASS_TIME
		TYPE_TIME_RANGE = 1 + CLASS_TIME
		TYPE_FORMULA = 0 + CLASS_FORMULA
		TYPE_USERID = 0 + CLASS_USERID
		TYPE_RFC822_TEXT = 2 + CLASS_TEXT
		
		TYPE_INVALID = 0 + CLASS_NOCOMPUTE
		TYPE_COMPOSITE = 1 + CLASS_NOCOMPUTE
		TYPE_COLLATION = 2 + CLASS_NOCOMPUTE
		TYPE_OBJECT = 3 + CLASS_NOCOMPUTE
		TYPE_NOTEREF_LIST = 4 + CLASS_NOCOMPUTE
		TYPE_VIEW_FORMAT = 5 + CLASS_NOCOMPUTE
		TYPE_ICON = 6 + CLASS_NOCOMPUTE
		TYPE_NOTELINK_LIST = 7 + CLASS_NOCOMPUTE
		TYPE_SIGNATURE = 8 + CLASS_NOCOMPUTE
		TYPE_SEAL = 9 + CLASS_NOCOMPUTE
		TYPE_SEALDATA = 10 + CLASS_NOCOMPUTE
		TYPE_SEAL_LIST = 11 + CLASS_NOCOMPUTE
		TYPE_HIGHLIGHTS = 12 + CLASS_NOCOMPUTE
		TYPE_WORKSHEET_DATA = 13 + CLASS_NOCOMPUTE
		TYPE_USERDATA = 14 + CLASS_NOCOMPUTE
		TYPE_QUERY = 15 + CLASS_NOCOMPUTE
		TYPE_ACTION = 16 + CLASS_NOCOMPUTE
		TYPE_ASSISTANT_INFO = 17 + CLASS_NOCOMPUTE
		TYPE_VIEWMAP_DATASET = 18 + CLASS_NOCOMPUTE
		TYPE_VIEWMAP_LAYOUT = 19 + CLASS_NOCOMPUTE
		TYPE_LSOBJECT = 20 + CLASS_NOCOMPUTE
		TYPE_HTML = 21 + CLASS_NOCOMPUTE
		TYPE_SCHED_LIST = 22 + CLASS_NOCOMPUTE
		TYPE_CALENDAR_FORMAT = 24 + CLASS_NOCOMPUTE
		TYPE_MIME_PART = 25 + CLASS_NOCOMPUTE
		
		# Update flags
		UPDATE_FORCE = 0x0001
		UPDATE_NAME_KEY_WARNING = 0x0002
		UPDATE_NOCOMMIT = 0x0004
		UPDATE_NOREVISION = 0x0100
		UPDATE_NOSTUB = 0x0200
		UPDATE_INCREMENTAL = 0x4000
		UPDATE_DELETED = 0x8000
		UPDATE_DUPLICATES = 0
		UPDATE_SHARE_SECOND = 0x00200000
		UPDATE_SHARE_OBJECTS = 0x00400000
		
		# MIME part types
		MIME_PART_PROLOG = 1
		MIME_PART_BODY = 2
		MIME_PART_EPILOG = 3
		MIME_PART_RETRIEVE_INFO = 4
		MIME_PART_MESSAGE = 5
		
		MIME_PART_HAS_BOUNDARY = 0x00000001
		MIME_PART_HAS_HEADERS = 0x00000002
		MIME_PART_BODY_IN_DBOBJECT = 0x00000004
		MIME_PART_SHARED_DBOBJECT = 0x00000008
		MIME_PART_SKIP_FOR_CONVERSION = 0x00000010
		
		# Replica stuff
		REPLICA_ID_UNINITIALIZED = 0x00000000
		REPLICA_ID_CATALOG = 0x00003301
		REPLICA_ID_EVENT = 0x00003302
		REPLICA_ID_NEVERREPLACE = 0x00001601
		
		# NIFFindDesignNoteExt flag sets
		DFLAGPAT_V4SEARCHBAR = "(+Qq-Bst5nmz*"
		DFLAGPAT_SEARCHBAR = "(+QM-st5nmz*"
		DFLAGPAT_FORM = "-FQMUGXWy#i:|@0nK;g~%z^"
		DFLAGPAT_FORM_OR_SIMILAR = "-FMGXy#i=:|@0K;g~%z^"
		DFLAGPAT_FORM_OR_PAGE = "-FQMUGXy#i:|@0nK;g~%z^"
		DFLAGPAT_FORM_MENUABLE = "-FQMUGXWy#i:|@40nK;g~%z^}"
		DFLAGPAT_FORM_ALL_VERSIONS = "-FQMUGXWy#i:|@K;g~%z^}"
		DFLAGPAT_PRINTFORM_ALL_VERSIONS = "+?"
		DFLAGPAT_FIELD = "-FQMUGXWy#i@0nK;g~%z^"
		DFLAGPAT_FIELD_ALL_VERSIONS = "-FQMUGXWy#i@K;g~%z^}"
		DFLAGPAT_TOOLSRUNMACRO = "-QXMBESIst5nmz{"
		DFLAGPAT_AGENTSLIST = "-QXstmz{"
		DFLAGPAT_PASTEAGENTS = "+I"
		DFLAGPAT_SCRIPTLIB = "+sh."
		DFLAGPAT_SCRIPTLIB_LS = "(+s-jh.*"
		DFLAGPAT_SCRIPTLIB_JS = "*sj"
		DFLAGPAT_SCRIPTLIB_SERVER_JS = "+."
		DFLAGPAT_DATABASESCRIPT = "+t"
		DFLAGPAT_SUBFORM = "(+U-40n*"
		DFLAGPAT_SUBFORM_DESIGN = "(+U-40*"
		DFLAGPAT_SUBFORM_ALL_VERSIONS = "+U"
		DFLAGPAT_DBRUNMACRO = "+BS"
		DFLAGPAT_COMPOSE = "-C40n"
		DFLAGPAT_NOHIDDENNOTES = "-n"
		DFLAGPAT_NOHIDDENWEB = "-w"
		DFLAGPAT_QUERYBYFORM = "-DU40gnyz{:|"
		DFLAGPAT_PRESERVE = "+P"
		DFLAGPAT_SUBADD = "(+-40*UA"
		DFLAGPAT_SUBNEW = "(+-40*UN"
		DFLAGPAT_VIEW = "-FG40n^"
		DFLAGPAT_VIEW_MENUABLE = "-FQMUGXWy#i@40nK;g~%z^}"
		DFLAGPAT_VIEW_ALL_VERSIONS = "-FG^"
		DFLAGPAT_VIEW_DESIGN = "-FG40^"
		DFLAGPAT_NOTHIDDEN = "-40n"
		DFLAGPAT_FOLDER = "(+-04n*F"
		DFLAGPAT_FOLDER_DESIGN = "(+-04*F"
		DFLAGPAT_FOLDER_ALL_VERSIONS = "*F"
		DFLAGPAT_CALENDAR = "*c"
		DFLAGPAT_SHAREDVIEWS = "-FGV^40n"
		DFLAGPAT_SHAREDVIEWSFOLDERS = "-G^V40p"
		DFLAGPAT_SHAREDWEBVIEWS = "-FGV40wp^"
		DFLAGPAT_SHAREDWEBVIEWSFOLDERS = "-GV40wp^"
		DFLAGPAT_VIEWS_AND_FOLDERS = "-G40n^"
		DFLAGPAT_VIEWS_AND_FOLDERS_DESIGN = "-G40^"
		DFLAGPAT_SHARED_COLS = "(+-*^"
		
		DFLAGPAT_VIEWMAP = "(+-04n*G"
		DFLAGPAT_VIEWMAP_ALL_VERSIONS = "*G"
		DFLAGPAT_VIEWMAPWEB = "(+-04w*G"
		DFLAGPAT_VIEWMAP_DESIGN = "(+-04*G"
		
		DFLAGPAT_WEBPAGE = "(+-*W"
		DFLAGPAT_WEBPAGE_NOTES = "(+W-n*"
		DFLAGPAT_WEBPAGE_WEB = "(+W-w*"
		
		DFLAGPAT_OTHER_DLG = "(+-04n*H"
		
		DFLAGPAT_CATEGORIZED_VIEW = "(+-04n*T"
		DFLAGPAT_DEFAULT_DESIGN = "+d"
		
		DFLAGPAT_FRAMESET = "(+-*#"
		DFLAGPAT_FRAMESET_NOTES = "(+#-n*"
		DFLAGPAT_FRAMESET_WEB = "(+#-w*"
		
		DFLAGPAT_SITEMAP = "+m"
		DFLAGPAT_SITEMAP_NOTES = "(+m-n*"
		DFLAGPAT_SITEMAP_WEB = "(+m-w*"
		
		DFLAGPAT_IMAGE_RESOURCE = "+i"
		DFLAGPAT_IMAGE_RES_NOTES = "(+i-n~*"
		DFLAGPAT_IMAGE_RES_WEB = "(+i-w~*"
		DFLAGPAT_IMAGE_WELL_RESOURCE = "(+-*iv"
		DFLAGPAT_IMAGE_WELL_NOTES = "(+-n*iv"
		DFLAGPAT_IMAGE_WELL_WEB = "(+-w*iv"
		
		DFLAGPAT_JAVA_RESOURCE = "+@"
		DFLAGPAT_JAVA_RESOURCE_NOTES = "(+@-n*"
		DFLAGPAT_JAVA_RESOURCE_WEB = "(+@-w*"
		
		DFLAGPAT_XSPPAGE = "*gK"
		DFLAGPAT_XSPPAGE_WEB = "(+-w*gK"
		DFLAGPAT_XSPPAGE_NOTES = "(+-n*gK"
		DFLAGPAT_XSPPAGE_NOPROPS = "(+-2*gK"
		DFLAGPAT_XSPPAGE_NOPROPS_WEB = "(+-2w*gK"
		DFLAGPAT_XSPPAGE_NOPROPS_NOTES = "(+-2n*gK"
		DFLAGPAT_XSPCC = "*g;"
		DFLAGPAT_XSPCC_WEB = "(+-w*g;"
		DFLAGPAT_XSPCC_NOTES = "(+-n*g;"
		
		DFLAGPAT_DATA_CONNECTION_RESOURCE = "+k"
		DFLAGPAT_DB2ACCESSVIEW = "+z"
		
		DFLAGPAT_STYLE_SHEET_RESOURCE = "+="
		DFLAGPAT_STYLE_SHEETS_NOTES = "(+=-n*"
		DFLAGPAT_STYLE_SHEETS_WEB = "(+=-w*"
		
		DFLAGPAT_FILE = "+g-K[];`"
		DFLAGPAT_FILE_DL = "(+g-~K[];`*"
		DFLAGPAT_FILE_NOTES = "(+g-K[];n`*"
		DFLAGPAT_FILE_WEB = "(+g-K[];w`*"
		DFLAGPAT_HTMLFILES = "(+-*g>"
		DFLAGPAT_HTMLFILES_NOTES = "(+-n*g>"
		DFLAGPAT_HTMLFILES_WEB = "(+-w*g>"
		DFLAGPAT_FILE_ELEMS = "(+gi|=-/*"
		
		DFLAGPAT_SERVLET = "+z"
		DFLAGPAT_SERVLET_NOTES = "(+z-n*"
		DFLAGPAT_SERVLET_WEB = "(+z-w*"
		DFLAGPAT_WEBSERVICE = "+{"
		DFLAGPAT_JAVA_WEBSERVICE = "(+Jj-*{"
		DFLAGPAT_LS_WEBSERVICE = "*{L"
		
		DFLAGPAT_JSP = "(+-*g<"
		
		DFLAGPAT_STYLEKIT = "(+-*g`"
		DFLAGPAT_STYLEKIT_NOTES = "(+-n*g`"
		DFLAGPAT_STYLEKIT_WEB = "(+-w*g`"
		
		DFLAGPAT_WIDGET = "(+-*g_"
		DFLAGPAT_WIDGET_NOTES = "(+-n*g_"
		DFLAGPAT_WIDGET_WEB = "(+-w*g_"
		
		DFLAGPAT_SACTIONS_DESIGN = "+y"
		DFLAGPAT_SACTIONS_WEB = "(+-0*y"
		DFLAGPAT_SACTIONS_NOTES = "(+-0*y"
		
		DFLAGPART_COMPDEF = "+:"
		DFLAGPAT_COMPAPP = "+|"
		
		# Web server patterns
		DFLAGPAT_NONWEB = "+w80stVXp^"
		DFLAGPAT_NONWEB_EXCLUDE = "-w80stVXp^"
		DFLAGPAT_AGENTSWEB = "(+-QXstmz{*"
		DFLAGPAT_AGNTORWEBSVCWEB = "(+-QXstmz*"
		DFLAGPAT_FORMSWEB = "+{"
		DFLAGPAT_SUBFORMSWEB = "+U"
		DFLAGPAT_FRAMESETWEB = "+#"
		DFLAGPAT_PAGESWEB = "+W"
		DFLAGPAT_VIEWSWEB = "-G"
		DFLAGPAT_NAVIGATORSWEB = "+G"
		DFLAGPAT_SHAREDFIELDSWEB = "*"
		DFLAGPAT_ALLWEB = "*"
		DFLAGPAT_NO_FILERES_DIRS = "-/"
		DFLAGPAT_FIRSTPATTERNCHAR = "(+-*"
		DFLAGPAT_WEBHYBRIDDB = "+%"
		
		# Item flags
		ITEM_SUMMARY = 0x0004
	end
end